A --Aggregate Functions + basic grouping--

--1 Creating Database

Create Database Olist_Analytics;

--2 DATABASE VALIDATION Check all tables available in the Olist database

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

--3 Select Database

use Olist_Analytics;

--4 CUSTOMER DATASET Size, Check how many customer records we have
SELECT COUNT(*) AS total_customers
FROM olist_customers_dataset;

-- 5  ORDER DATASET SIZE, Check how many orders we have

SELECT COUNT(*) AS total_orders
FROM olist_orders_dataset;

-- 5 UNIQUE CUSTOMER COUNT, Check how many distinct customers we actually have

SELECT COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM olist_customers_dataset;

-- 6 REPEAT CUSTOMER CHECK, Find how many customer records are beyond the first purchase

SELECT
COUNT(*) - COUNT(DISTINCT customer_unique_id) AS repeat_customer_records
FROM olist_customers_dataset;

-- 7 REPEAT CUSTOMER COUNT, Find customers who appear in more than one record

SELECT COUNT(*) AS repeat_customers
FROM (
    SELECT customer_unique_id
    FROM olist_customers_dataset
    GROUP BY customer_unique_id
    HAVING COUNT(*) > 1) AS repeat_customers;

-- 8 REPEAT CUSTOMER RATE, Calculate the percentage of unique customers who are repeat customers

SELECT 2997.0 / 96096 * 100 AS repeat_customer_rate;

-- 9 Show each order_status and how many orders belong to it.

SELECT order_status,count(*) As Order_count
FROM olist_orders_dataset
GROUP BY order_status;

--10 TOTAL SALES REVENUE, Calculate total revenue generated from product sales

Select sum(price) as TOTAL_SALES_REVENUE
from olist_order_items_dataset;

--11 AVERAGE ORDER VALUE (AOV), Calculate average sales value generated per order

SELECT SUM(price) / COUNT(DISTINCT order_id) AS average_order_value
FROM olist_order_items_dataset;

--12 TOTAL FREIGHT COST, Calculate total freight cost paid across all order items

Select sum(freight_value) as total_freight_cost
from olist_order_items_dataset;

--13 Average freight cost per order.

select SUM(freight_value) / COUNT(DISTINCT order_id)
from olist_order_items_dataset;
 
--14 Average item price.

select AVG(price) 
from olist_order_items_dataset;


--B JOINs


--15 Sales by Product Category, total sales revenue generated by each product category, and show highest-selling categories first.

Select sum(price) as total_sales_revenue,product_category_name
from olist_order_items_dataset
inner join olist_products_dataset
on olist_order_items_dataset.product_id=olist_products_dataset.product_id
group by product_category_name
order by total_sales_revenue desc;

--16 Sales by payment type — finding how much payment value came through each payment type.

Select payment_type,
sum(payment_value)
from olist_order_payments_dataset
group by payment_type

--17 Payment type distribution, Find how many payment transactions were made using each payment type.

select payment_type,count (payment_installments)as payment_transaction 
from olist_order_payments_dataset
group by payment_type

--18 Average Payment Value by Payment Type, Finding the average payment value for each payment type.

select avg(payment_value) as Average_payment
from olist_order_payments_dataset
group by payment_type

--19 CUSTOMER ORDER FREQUENCY, Calculating how many orders each unique customer has placed.

select customer_unique_id,
count (order_id) as order_count
from olist_orders_dataset as o
left join olist_customers_dataset as c
on o.customer_id = c.customer_id
group by customer_unique_id;

-- 20 HIGHEST CUSTOMER SALES
-- Calculate total sales generated by each customer

SELECT c.customer_unique_id,
       SUM(oi.price) AS total_sales
FROM olist_customers_dataset AS c
INNER JOIN olist_orders_dataset AS o
ON c.customer_id = o.customer_id
INNER JOIN olist_order_items_dataset AS oi
 ON o.order_id = oi.order_id
GROUP BY c.customer_unique_id
ORDER BY total_sales DESC;

-- 21 — Customer Spending vs Order Frequency, find customers who placed more than 1 order and calculate their total sales.

Select customer_unique_id, sum(oi.price) as total_spending
FROM olist_customers_dataset AS c
JOIN olist_orders_dataset AS o
ON c.customer_id = o.customer_id

JOIN olist_order_items_dataset AS oi
ON o.order_id = oi.order_id
group by customer_unique_id 
having count (distinct o.order_id) >1
order by total_spending Desc;

--22 Monthly Revenue Trend, Calculating the total sales revenue for each month based on the order purchase date.

SELECT
YEAR(o.order_purchase_timestamp) AS order_year,
MONTH(o.order_purchase_timestamp) AS order_month,
SUM(oi.price) AS total_sales
FROM olist_orders_dataset AS o
JOIN olist_order_items_dataset AS oi
ON o.order_id = oi.order_id
GROUP BY
YEAR(o.order_purchase_timestamp),
MONTH(o.order_purchase_timestamp)
ORDER BY order_year, order_month;

--23 Delivery Time Analysis, average number of days it takes to deliver an order to the customer?

SELECT AVG( DATEDIFF( DAY,o.order_purchase_timestamp,o.order_delivered_customer_date)) AS average_delivery_days
FROM olist_orders_dataset AS o
WHERE o.order_delivered_customer_date IS NOT NULL;

-- 24 REVIEW SCORE VS SALES,Analyze average order value by review score

SELECT r.review_score,
AVG(oi.price) AS average_item_sales,
SUM(oi.price) AS total_sales
FROM olist_order_reviews_dataset AS r
JOIN olist_order_items_dataset AS oi
ON r.order_id = oi.order_id
GROUP BY r.review_score
ORDER BY r.review_score DESC;

-- 25 SELLER PERFORMANCE, Find top sellers by total sales and number of orders

SELECT TOP 20
COUNT(DISTINCT oi.order_id) AS total_orders,
SUM(oi.price) AS total_sales
FROM olist_order_items_dataset AS oi
GROUP BY oi.seller_id
ORDER BY total_sales DESC;

 -- 26 STATE PERFORMANCE,Compare sales and order volume across customer states.

SELECT c.customer_state,
COUNT(DISTINCT o.order_id) AS total_orders,
SUM(oi.price) AS total_sales
FROM olist_customers_dataset AS c
JOIN olist_orders_dataset AS o
ON c.customer_id = o.customer_id
JOIN olist_order_items_dataset AS oi
ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY total_sales DESC;

-- 27 CANCELLATION AND DELIVERY ISSUES, Analyze cancelled and undelivered orders

SELECT
COUNT(*) AS total_orders,
SUM(CASE
WHEN order_status = 'canceled'
THEN 1 ELSE 0
END) AS cancelled_orders,
SUM(CASE
WHEN order_delivered_customer_date IS NULL
AND order_status NOT IN ('canceled', 'unavailable')
THEN 1 ELSE 0
END) AS undelivered_orders
FROM olist_orders_dataset;

-- 28 TOP PRODUCTS,Find the top products based on total sales and number of orders

SELECT TOP 20
oi.product_id,
COUNT(DISTINCT oi.order_id) AS total_orders,
SUM(oi.price) AS total_sales
FROM olist_order_items_dataset AS oi
GROUP BY oi.product_id
ORDER BY total_sales DESC;

-- 29 ADVANCED CUSTOMER ANALYSIS,Rank customers by spending within their state

WITH customer_sales AS (
SELECT
c.customer_unique_id,
c.customer_state,
SUM(oi.price) AS total_spending
FROM olist_customers_dataset AS c
JOIN olist_orders_dataset AS o
ON c.customer_id = o.customer_id
JOIN olist_order_items_dataset AS oi
ON o.order_id = oi.order_id
GROUP BY
c.customer_unique_id,
c.customer_state)

SELECT
customer_unique_id,
customer_state,
total_spending,
RANK() OVER (
PARTITION BY customer_state
ORDER BY total_spending DESC) AS spending_rank
FROM customer_sales
ORDER BY customer_state,spending_rank;

-- 30 CUSTOMER LIFETIME VALUE BY STATE,Calculate average customer spending in each state

WITH customer_value AS (
SELECT
c.customer_unique_id,
c.customer_state,
SUM(oi.price) AS customer_spending
FROM olist_customers_dataset AS c
JOIN olist_orders_dataset AS o
ON c.customer_id = o.customer_id
JOIN olist_order_items_dataset AS oi
ON o.order_id = oi.order_id
GROUP BY
c.customer_unique_id,
c.customer_state)

SELECT
customer_state,
AVG(customer_spending) AS average_customer_lifetime_value
FROM customer_value
GROUP BY customer_state
ORDER BY average_customer_lifetime_value DESC;